---
- name: Print value of the file
  debug:
    msg: "{{ fileValue.split('\n') }}"
  when: fileValue != ''
  
- name: Output the content of the file
  command: echo "{{ fileValue }}"
  register: output_echo_vars
  
- name: Print value of the file
  command: echo "{{item}}"
  with_items:
    - "{{ fileValue.split('\n') }}"
  when: fileValue != ''
