---
- name: download file from GIT reporsitory
  get_url:
    url: '{{ fileValue }}'
    dest: "/tmp/{{fileValue.split('/')[-1]}}"
    mode: 0777
    remote_src: yes
  when: filepresent and gitorlocal

- name: Copy the file from remote to server
  fetch:
    src: "/tmp/{{fileValue.split('/')[-1]}}"
    dest: "/tmp/{{fileValue.split('/')[-1]}}"
    flat: yes
  when: filepresent and gitorlocal

- name: Read the contents of the git file
  set_fact: 
    filecontents: "{{ lookup('file', '/tmp/'+fileValue.split('/')[-1]) }}"
  when: filepresent and gitorlocal

- name: Read the contents of the local file
  set_fact: 
    filecontents: "{{ lookup('file', filelocation }}"
  when: filepresent and not gitorlocal
  
- name: Print value of the file
  command: echo "{{item}}"
  with_items:
    - "{{ filecontents.split('\n') }}"
  when: filepresent
  
- name: Remove the temparory file
  file:
    path: "/tmp/+{{fileValue.split('/')[-1]}}"
    state: absent
  when: filepresent  