---
- name: download file from GIT reporsitory
  get_url:
    url: '{{ fileValue }}'
    dest: "/tmp/{{fileValue.split('/')[-1]}}"
    mode: 0777
    remote_src: yes
  when: filepresent

- name: Copy the file from remote to server
  fetch:
    src: "/tmp/{{fileValue.split('/')[-1]}}"
    dest: "/tmp/{{fileValue.split('/')[-1]}}"
    flat: yes

- name: Print value of the file
  debug:
    msg: "{{ lookup('file', '/tmp/'+fileValue.split('/')[-1]).split('\n') }}"
  register: filecontent
  when: filepresent	